language: node_js
node_js: node

cache:
  directories:
    - node_modules

install:
  - yarn

before_script:

script:
  - yarn run build

after_script:
  - cd ./build
  - git init
  - git config user.name "WhiteAce"
  - git config user.email "whiteace@yeah.net"
  - git add .
  - git commit -m "Update tools"
  - git push --force --quiet "https://b6be0fc808545366d89ecf385c771b339137e63e@github.com/ziqinH/ziqinH.github.io.git" master:master

branches:
  only:
    - gh-pages 
