language: node_js
node_js:
  - "stable"

cache:
  directories:
    - node_modules

install:
  - yarn

before_script:

script:
  - npm run build

after_script:
  - cd ./build
  - git init
  - git config user.name "WhiteAce"
  - git config user.email "whiteace@yeah.net"
  - git add .
  - git commit -m "Update tools"
  - git push --force --quiet "https://${GH_TOKEN}@github.com/ziqinH/ziqinH.github.io.git" master:master

branches:
  only:
    - gh-pages 
